### PR TITLE
Update guide.md

### PR DESCRIPTION
**Pull request by BillybobIII**
Small thing i lost the other stuff when i refreshed page while still in edit just this for now

### CODE REVIEW

**Comment by tombertrand** [comment]
you may add some of those details?

´´´ export const attackBonuPercentsFromWeightMap = {
  light: -15,
  normal: 0,
  heavy: 25,
  "Super heavy": 35,
};
export const getAttackSpeedBonusFromStringMap = {
  light: 20,
  normal: 0,
  heavy: -15,
  "Super heavy": -20,
};

export const getWeaponWeightbyKind = (kind: number): string => {
  let weights = ["light", "normal", "heavy", "Super heavy"];

  if (typeof kind !== "number") return;

  if (Types.Entities.LightWeapons.includes(kind)) {
    return weights[0];
  } else if (Types.Entities.HeavyWeapons.includes(kind)) {
    return weights[2];
  } else if (Types.Entities.SuperHeavyWeapons.includes(kind)) {
    return weights[3];
  } else {
    return weights[1];
  }´´´

**Comment by BillybobIII** [comment]
Hold on so light weapons +15% attack speed heavy weapons have a 25% penalty? Normal is just normal attack speed

**Comment by BillybobIII** [comment]
Oh wait hold on it read it wrong 15% penalty for heavy super heavy 20% penalty and light is 20% boost and normal is just normal sry i got it

**Comment by tombertrand** [comment]
do you think you can rebase on master and resolve conflicts using master

**Comment by tombertrand** [comment]
image

**Pull request closed without merging**
